In [11]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np
import random

In [26]:
testarray = np.zeros((5, 7))

testarray.shape[1]

for row in np.arange(testarray.shape[0]):
    for column in np.arange(testarray.shape[1]):
        testarray[row, column] = random.choice([0, 0, 1])

print(testarray)

[[1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0.]
 [1. 0. 1. 0. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


<h2>Algorithm X</h2>
<ol>
<li>
</ol>

<h2>Some optimisation ideas for Algorithm X</h2>
<ul>
<li> First check if there are any columns that are all filled with 0s - that means there is no cover for that column and we can't get exact coverage
<li> 
</ul>